### ISSUE TITLE
计算单元格的8个属性的问题

### ISSUE THREAD

**Issue by wdxpython** [YannZyl/Apollo-Note#2]
![image](https://user-images.githubusercontent.com/43343284/50624075-65713480-0f57-11e9-823c-cefbd11f3413.png)
您好，我在看到计算单元格8个属性的代码时候，不是应该用映射之后的单元格吗？为什么又把坐标转到以激光雷达为中心，前后左右各60这里来了呢？我计算出来的center_x的范围是（-60，60），不是应该用width x height 上的单元格吗？麻烦您了

**Comment by wdxpython** [comment]
您好，如果计算的是每个单元格的中心对应的激光雷达原始的点云坐标相对于以雷达为圆心的方向和距离的话，这个距离为什么又要除以60再减去0.5呢 ？麻烦了，这里没看懂

**Comment by wdxpython** [comment]
![image](https://user-images.githubusercontent.com/43343284/50624560-82f4cd00-0f5c-11e9-901a-15b54a949ba2.png)

**Comment by YannZyl** [comment]
因为我不是主激光雷达，所以只能给您一些自己的看法。
1. 第一个问题为什么计算每个栅格和”主车”/(0,0)左上角栅格的direction和distance需要反算到物理距离，也就是你说的激光雷达坐标。 其实我的想法是这样的，不论是栅格距离/方向还是物理距离/方向，两种方法其实都可以，这只是取决于你网络训练数据的形式而已，训练用什么方式，inference就用什么方式。还有一个可能的说法是，像apollo一样反算到物理坐标计算的方向和距离可能更有实际意义。
2. 为什么计算栅格方向特征需要除以60以后减去0.5。我个人觉得一个合理的说法是数据的“中心化”。direction计算完arctan以后除以2pi，数据规范化到[0,1]之间；distance我们可以知道他的实际距离大致为[0, 60*sqrt(2)]，所以除以60减0.5以后大致规范化到[-0.5,0.91]之间。至于为什么不像direction一样除以sqrt(2)，可能后者更好理解吧，只是猜测哈哈哈
3. 栅格里面的距离a和对应实际物理场景下的距离b比较哪个大？这个我不是特别明白你的意思，这两者本身就是映射关系，直接比较他们在各自参考系下的距离其实没什么意义。
这些是我个人的看法，平时没有真正的去落实研究，所以只能理论上分析一下，实际有可能是错的，欢迎指正~

**Comment by wdxpython** [comment]
好的，我之前不敢这样想，听您这样说就懂了，非常感谢，谢谢您的细心讲解。

**Comment by YannZyl** [comment]
抱歉纠正一下，direction计算arctan除以2pi规范化到[-0.5,0.5]而不是[0,1]。比栅格计算得到的[0,pi/2]数据压缩程度也要小些。
